[tool.ruff]
target-version = "py312"
line-length = 120
exclude = ["venv", "build", "dist"]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "BLE001",
    "C901",
    "COM812",
    "D",
    "ISC001",
    "PLR0912",
    "PLR0913",
    "PLR0915",
    "S101",
    "UP040",
] # TODO leave only "COM812", "ANN102", "UP040" in ignores

[tool.mypy]
python_version = "3.12"
strict = true
plugins = ["pydantic.mypy"]
exclude = "venv/"

[[tool.mypy.overrides]]
module = [
    "pyaudiowpatch",
    "pyvirtualcam",
    "sounddevice",
    "zmq",
    "scipy",
    "websockets",
]
ignore_missing_imports = true
